language: scala
scala:
- 2.11.4
jdk:
- oraclejdk8
- oraclejdk7
script:
- sbt clean
- sbt compile
- sbt test
after_success:
- ! '[[ $TRAVIS_BRANCH == "master" ]] && { sbt publish; };'
env:
  global:
  - secure: uqn3s349gvKStDiRGd4L22r1ZT8EFPUC0++f2NZ9eLVfLSD5+Yi6PMhjrWXItVmv9MkSE6XXs7XrR2CHlB7twXyQFHCMnq1y1Lz6MnYRrN9AyF925Bv26jyGoBxiHaow0YYQx3KfvNUvkwZ2msPY6QPM/hR9vUi2d4s/wg1dWJ4=
  - secure: opSfzj7W/Y+e17hlybzcOp2CuFoIibP6fv8yH09imAj9+/LreC+sOz+EYU0mANxuj2xrrw7UxKicAO50zqQi9+KXnYJa4yMwHTU3bkGV++JnRimyAEzuAwkFFykuV4qMbBTYl54XWOvI5pdZODH1eUooF4AgJvPJNbQf3lmvluY=
