language: scala
scala:
- 2.11.4
jdk:
- oraclejdk8
- oraclejdk7
before_install:
- openssl aes-256-cbc -K $encrypted_d6f8ddd0db9e_key -iv $encrypted_d6f8ddd0db9e_iv
  -in project/keys.tar.gz.enc -out project/keys.tar.gz -d
- tar -xf project/keys.tar.gz
script:
- sbt clean
- sbt compile
- sbt test
after_success:
- test "${TRAVIS_JDK_VERSION}" = 'oraclejdk8' && sbt publishSigned
env:
  global:
  - secure: uqn3s349gvKStDiRGd4L22r1ZT8EFPUC0++f2NZ9eLVfLSD5+Yi6PMhjrWXItVmv9MkSE6XXs7XrR2CHlB7twXyQFHCMnq1y1Lz6MnYRrN9AyF925Bv26jyGoBxiHaow0YYQx3KfvNUvkwZ2msPY6QPM/hR9vUi2d4s/wg1dWJ4=
  - secure: opSfzj7W/Y+e17hlybzcOp2CuFoIibP6fv8yH09imAj9+/LreC+sOz+EYU0mANxuj2xrrw7UxKicAO50zqQi9+KXnYJa4yMwHTU3bkGV++JnRimyAEzuAwkFFykuV4qMbBTYl54XWOvI5pdZODH1eUooF4AgJvPJNbQf3lmvluY=
